pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                 sh 'echo this is build'
            }
        }
        stage('Test') {
            steps {
                 sh 'echo this is test'
            }
        }
        stage('Deploy') {
            steps {
                 sh 'echo this is deply'
            }
        }
    }

    post{
        always{
            echo 'I will always say Hello again!'
        }
        failure{
            echo 'build failed!'
        }

        success{
            echo 'build success!'
        }

    }
}