pipeline{
    agent none
    
    stages {
        stage('Build') {
            steps {
                sudo 'echo this is build'
            }
        }

         stage('Test'){
            steps {
                sudo 'echo this is test'
            }
        }

         stage('Build'){
            steps {
                sudo 'echo this is deploybuild'
            }
        }
    }

}