pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                 sudo 'echo this is build'
            }
        }
        stage('Test') {
            steps {
                 sudo 'echo this is test'
            }
        }
        stage('Deploy') {
            steps {
                 sudo 'echo this is deply'
            }
        }
    }
}