pipeline{
    agent {
        label 'AGENT-1'
    }

    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
     stages {
        stage("Build") {
            steps {
                sh "echo this is build"
                sh "sleep 10"
            }
        }

        stage("Test") {
            steps {
                sh "echo this is test"
            }
        }

         stage("Deploy") {
            steps {
                sh "echo this is Deploy"
            }
        }
     }

     post {
        always {
            echo "this is always says hiii"
            deleteDir()
        }
        failure{
            echo "build is failed"
        }
        success{
            echo "build is success"
        }
     }
}