pipeline{
    agent {
        label 'AGENT-1'
    }
     stages {
        stage("Build") {
            steps {
                sh "echo this is build"
            }
        }

        stage("Test") {
            steps {
                sh "echo this is test"
            }
        }

         stage("Deploy") {
            steps {
                sh "echo this is Deploy"
            }
        }
     }

     post {
        always {
            echo "this is always says hiii"
        }
        failure{
            echo "build is failed"
        }
        success{
            echo "build is success"
        }
     }
}